/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

/**
 *
 * @author Bruno
 */
public class View extends javax.swing.JPanel {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moduloGerencial = new javax.swing.JTabbedPane();
        importarInserir = new javax.swing.JPanel();
        importarLogging = new javax.swing.JButton();
        inserirDados = new javax.swing.JButton();
        console = new javax.swing.JTextField();
        relatorios = new javax.swing.JPanel();
        data_label = new javax.swing.JLabel();
        data_formatada = new javax.swing.JFormattedTextField();
        seletor_parquimetro = new javax.swing.JLabel();
        parquimetro_selecionado = new javax.swing.JComboBox<>();
        scroll_relatorios = new javax.swing.JScrollPane();
        relatorio = new javax.swing.JTextArea();
        graficos = new javax.swing.JPanel();
        subgraficos = new javax.swing.JTabbedPane();
        geral = new javax.swing.JPanel();
        data_inicio_label = new javax.swing.JLabel();
        data_inicio_text = new javax.swing.JFormattedTextField();
        data_fim_label = new javax.swing.JLabel();
        data_fim_text = new javax.swing.JFormattedTextField();
        porParquimetro = new javax.swing.JPanel();
        parquimetro_grafico = new javax.swing.JLabel();
        seletor_parquimetro_grafico = new javax.swing.JComboBox<>();
        endereco_label = new javax.swing.JLabel();
        endereco_texto = new javax.swing.JTextField();
        scroll_parquimetro = new javax.swing.JScrollPane();
        grafico_parquimetro = new javax.swing.JTextArea();
        ano_label = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        importarLogging.setText("Importar arquivos de logging");

        inserirDados.setText("Inserir dados importados");

        console.setEditable(false);

        javax.swing.GroupLayout importarInserirLayout = new javax.swing.GroupLayout(importarInserir);
        importarInserir.setLayout(importarInserirLayout);
        importarInserirLayout.setHorizontalGroup(
            importarInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importarInserirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(importarInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(console)
                    .addGroup(importarInserirLayout.createSequentialGroup()
                        .addComponent(importarLogging, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(inserirDados, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        importarInserirLayout.setVerticalGroup(
            importarInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importarInserirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(importarInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importarLogging)
                    .addComponent(inserirDados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(console, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        moduloGerencial.addTab("Importar/Inserir", importarInserir);

        data_label.setText("Data");

        data_formatada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        seletor_parquimetro.setText("Parquímetro");

        parquimetro_selecionado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        relatorio.setEditable(false);
        relatorio.setColumns(20);
        relatorio.setRows(5);
        scroll_relatorios.setViewportView(relatorio);

        javax.swing.GroupLayout relatoriosLayout = new javax.swing.GroupLayout(relatorios);
        relatorios.setLayout(relatoriosLayout);
        relatoriosLayout.setHorizontalGroup(
            relatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(relatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll_relatorios)
                    .addGroup(relatoriosLayout.createSequentialGroup()
                        .addComponent(data_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(data_formatada, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seletor_parquimetro)
                        .addGap(18, 18, 18)
                        .addComponent(parquimetro_selecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 229, Short.MAX_VALUE)))
                .addContainerGap())
        );
        relatoriosLayout.setVerticalGroup(
            relatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(relatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(data_label)
                    .addComponent(data_formatada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seletor_parquimetro)
                    .addComponent(parquimetro_selecionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll_relatorios, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        moduloGerencial.addTab("Relatórios", relatorios);

        data_inicio_label.setText("Data de início");

        data_inicio_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        data_fim_label.setText("Data de fim");

        data_fim_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        javax.swing.GroupLayout geralLayout = new javax.swing.GroupLayout(geral);
        geral.setLayout(geralLayout);
        geralLayout.setHorizontalGroup(
            geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(geralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(data_inicio_label)
                .addGap(18, 18, 18)
                .addComponent(data_inicio_text, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(data_fim_label)
                .addGap(18, 18, 18)
                .addComponent(data_fim_text, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        geralLayout.setVerticalGroup(
            geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(geralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(data_inicio_label)
                    .addComponent(data_inicio_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data_fim_label)
                    .addComponent(data_fim_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(237, Short.MAX_VALUE))
        );

        subgraficos.addTab("Geral", geral);

        parquimetro_grafico.setText("Parquímetro");

        seletor_parquimetro_grafico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        endereco_label.setText("Endereço");

        endereco_texto.setEditable(false);

        grafico_parquimetro.setEditable(false);
        grafico_parquimetro.setColumns(20);
        grafico_parquimetro.setRows(5);
        scroll_parquimetro.setViewportView(grafico_parquimetro);

        ano_label.setText("Ano");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy"))));

        javax.swing.GroupLayout porParquimetroLayout = new javax.swing.GroupLayout(porParquimetro);
        porParquimetro.setLayout(porParquimetroLayout);
        porParquimetroLayout.setHorizontalGroup(
            porParquimetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(porParquimetroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(porParquimetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll_parquimetro)
                    .addGroup(porParquimetroLayout.createSequentialGroup()
                        .addGroup(porParquimetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parquimetro_grafico)
                            .addComponent(endereco_label))
                        .addGap(18, 18, 18)
                        .addGroup(porParquimetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endereco_texto)
                            .addGroup(porParquimetroLayout.createSequentialGroup()
                                .addComponent(seletor_parquimetro_grafico, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ano_label)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 254, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        porParquimetroLayout.setVerticalGroup(
            porParquimetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(porParquimetroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(porParquimetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parquimetro_grafico)
                    .addComponent(seletor_parquimetro_grafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ano_label)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(porParquimetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endereco_label)
                    .addComponent(endereco_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scroll_parquimetro, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
        );

        subgraficos.addTab("Por parquímetro", porParquimetro);

        javax.swing.GroupLayout graficosLayout = new javax.swing.GroupLayout(graficos);
        graficos.setLayout(graficosLayout);
        graficosLayout.setHorizontalGroup(
            graficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subgraficos)
        );
        graficosLayout.setVerticalGroup(
            graficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subgraficos)
        );

        moduloGerencial.addTab("Gráficos", graficos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moduloGerencial)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moduloGerencial)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ano_label;
    private javax.swing.JTextField console;
    private javax.swing.JLabel data_fim_label;
    private javax.swing.JFormattedTextField data_fim_text;
    private javax.swing.JFormattedTextField data_formatada;
    private javax.swing.JLabel data_inicio_label;
    private javax.swing.JFormattedTextField data_inicio_text;
    private javax.swing.JLabel data_label;
    private javax.swing.JLabel endereco_label;
    private javax.swing.JTextField endereco_texto;
    private javax.swing.JPanel geral;
    private javax.swing.JTextArea grafico_parquimetro;
    private javax.swing.JPanel graficos;
    private javax.swing.JPanel importarInserir;
    private javax.swing.JButton importarLogging;
    private javax.swing.JButton inserirDados;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JTabbedPane moduloGerencial;
    private javax.swing.JLabel parquimetro_grafico;
    private javax.swing.JComboBox<String> parquimetro_selecionado;
    private javax.swing.JPanel porParquimetro;
    private javax.swing.JTextArea relatorio;
    private javax.swing.JPanel relatorios;
    private javax.swing.JScrollPane scroll_parquimetro;
    private javax.swing.JScrollPane scroll_relatorios;
    private javax.swing.JLabel seletor_parquimetro;
    private javax.swing.JComboBox<String> seletor_parquimetro_grafico;
    private javax.swing.JTabbedPane subgraficos;
    // End of variables declaration//GEN-END:variables
}
