/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Bruno
 */
public class View extends javax.swing.JFrame {
    private GeradorDeGrafico geradorDeGrafico;
    
    
    /**
     * Creates new form NovaView
     */
    public View() {
        int[] serie = {1, 2, 3, 4};
        geradorDeGrafico = new GeradorDeGrafico(serie, 0, 3);
        initComponents();
    }
    
    public void associaController(Controller c){
        importarLogging.addActionListener(c); //TODO: Adicionar o listener pros outros botoes
        inserirDados.addActionListener(c); 
    }
    
    public JButton getImportarLogging()
    {
        return importarLogging;
    }
    
    public void mostra()
    {
        setVisible(true);
    }
    
    public void adicionaLog(String path)
    {
        console.setText(console.getText()
        + "\n"
        + "Adicionado arquivo: '"
        + path
        + "'");
    }
    
    public void dadosImportados(int qtdArquivos)
    {
        console.setText(qtdArquivos + " arquivos importados."); 
    }
    
    public void arquivoNaoEncontrado()
    {
        console.setText(console.getText()
        + "\n"
        + "Arquivo não encontrado"
        );
    }
    
    public void erroDeES()
    {
        console.setText(console.getText()
        + "\n"
        + "Erro de E/S"
        );
    }
    
    public void arquivoInvalido()
    {
        console.setText(console.getText()
        + "\n"
        + "Arquivo inválido"
        );
    }
    
    public JButton getInserirDados()
    {
        return inserirDados;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moduloGerencial = new javax.swing.JTabbedPane();
        importarInserir = new javax.swing.JPanel();
        importarLogging = new javax.swing.JButton();
        inserirDados = new javax.swing.JButton();
        console_panel = new javax.swing.JScrollPane();
        console = new javax.swing.JTextPane();
        relatorios = new javax.swing.JPanel();
        data_label = new javax.swing.JLabel();
        data_formatada = new javax.swing.JFormattedTextField();
        seletor_parquimetro = new javax.swing.JLabel();
        parquimetro_selecionado = new javax.swing.JComboBox<>();
        scroll_relatorios = new javax.swing.JScrollPane();
        relatorio = new javax.swing.JTextArea();
        graficos = new javax.swing.JPanel();
        subgraficos = new javax.swing.JTabbedPane();
        geral = new javax.swing.JPanel();
        data_inicio_label = new javax.swing.JLabel();
        data_inicio_text = new javax.swing.JFormattedTextField();
        data_fim_label = new javax.swing.JLabel();
        data_fim_text = new javax.swing.JFormattedTextField();
        painel_grafico = new java.awt.Panel();
        gerarGeral = new javax.swing.JButton();
        porParquimetro = new javax.swing.JPanel();
        parquimetro_grafico = new javax.swing.JLabel();
        seletor_parquimetro_grafico = new javax.swing.JComboBox<>();
        endereco_label = new javax.swing.JLabel();
        endereco_texto = new javax.swing.JTextField();
        scroll_parquimetro = new javax.swing.JScrollPane();
        grafico_parquimetro = new javax.swing.JTextArea();
        ano_label = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        importarLogging.setText("Importar arquivos de logging");

        inserirDados.setText("Inserir dados importados");

        console.setEditable(false);
        console_panel.setViewportView(console);

        javax.swing.GroupLayout importarInserirLayout = new javax.swing.GroupLayout(importarInserir);
        importarInserir.setLayout(importarInserirLayout);
        importarInserirLayout.setHorizontalGroup(
            importarInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importarInserirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(importarInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(console_panel)
                    .addGroup(importarInserirLayout.createSequentialGroup()
                        .addComponent(importarLogging, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inserirDados, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        importarInserirLayout.setVerticalGroup(
            importarInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importarInserirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(importarInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importarLogging)
                    .addComponent(inserirDados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(console_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
        );

        moduloGerencial.addTab("Importar/Inserir", importarInserir);

        data_label.setText("Data");

        data_formatada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        seletor_parquimetro.setText("Parquímetro");

        parquimetro_selecionado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        relatorio.setEditable(false);
        relatorio.setColumns(20);
        relatorio.setRows(5);
        scroll_relatorios.setViewportView(relatorio);

        javax.swing.GroupLayout relatoriosLayout = new javax.swing.GroupLayout(relatorios);
        relatorios.setLayout(relatoriosLayout);
        relatoriosLayout.setHorizontalGroup(
            relatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(relatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll_relatorios)
                    .addGroup(relatoriosLayout.createSequentialGroup()
                        .addComponent(data_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(data_formatada, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seletor_parquimetro)
                        .addGap(18, 18, 18)
                        .addComponent(parquimetro_selecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 173, Short.MAX_VALUE)))
                .addContainerGap())
        );
        relatoriosLayout.setVerticalGroup(
            relatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(relatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(data_label)
                    .addComponent(data_formatada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seletor_parquimetro)
                    .addComponent(parquimetro_selecionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll_relatorios, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );

        moduloGerencial.addTab("Relatórios", relatorios);

        data_inicio_label.setText("Data de início");

        data_inicio_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        data_fim_label.setText("Data de fim");

        data_fim_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        painel_grafico.setLayout(new java.awt.BorderLayout());

        gerarGeral.setText("Gerar");
        gerarGeral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gerarGeralMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout geralLayout = new javax.swing.GroupLayout(geral);
        geral.setLayout(geralLayout);
        geralLayout.setHorizontalGroup(
            geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(geralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painel_grafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(geralLayout.createSequentialGroup()
                        .addComponent(data_inicio_label)
                        .addGap(18, 18, 18)
                        .addComponent(data_inicio_text, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(data_fim_label)
                        .addGap(18, 18, 18)
                        .addComponent(data_fim_text, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gerarGeral)
                        .addGap(0, 102, Short.MAX_VALUE)))
                .addContainerGap())
        );
        geralLayout.setVerticalGroup(
            geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(geralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(data_inicio_label)
                    .addComponent(data_inicio_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data_fim_label)
                    .addComponent(data_fim_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gerarGeral))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painel_grafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        subgraficos.addTab("Geral", geral);

        parquimetro_grafico.setText("Parquímetro");

        seletor_parquimetro_grafico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        endereco_label.setText("Endereço");

        endereco_texto.setEditable(false);

        grafico_parquimetro.setEditable(false);
        grafico_parquimetro.setColumns(20);
        grafico_parquimetro.setRows(5);
        scroll_parquimetro.setViewportView(grafico_parquimetro);

        ano_label.setText("Ano");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy"))));

        javax.swing.GroupLayout porParquimetroLayout = new javax.swing.GroupLayout(porParquimetro);
        porParquimetro.setLayout(porParquimetroLayout);
        porParquimetroLayout.setHorizontalGroup(
            porParquimetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(porParquimetroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(porParquimetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll_parquimetro)
                    .addGroup(porParquimetroLayout.createSequentialGroup()
                        .addGroup(porParquimetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parquimetro_grafico)
                            .addComponent(endereco_label))
                        .addGap(18, 18, 18)
                        .addGroup(porParquimetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endereco_texto)
                            .addGroup(porParquimetroLayout.createSequentialGroup()
                                .addComponent(seletor_parquimetro_grafico, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ano_label)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 198, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        porParquimetroLayout.setVerticalGroup(
            porParquimetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(porParquimetroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(porParquimetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parquimetro_grafico)
                    .addComponent(seletor_parquimetro_grafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ano_label)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(porParquimetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endereco_label)
                    .addComponent(endereco_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scroll_parquimetro, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );

        subgraficos.addTab("Por parquímetro", porParquimetro);

        javax.swing.GroupLayout graficosLayout = new javax.swing.GroupLayout(graficos);
        graficos.setLayout(graficosLayout);
        graficosLayout.setHorizontalGroup(
            graficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subgraficos)
        );
        graficosLayout.setVerticalGroup(
            graficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subgraficos)
        );

        moduloGerencial.addTab("Gráficos", graficos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moduloGerencial)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moduloGerencial)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gerarGeralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerarGeralMouseClicked
        painel_grafico.removeAll();
        JPanel grafico = geradorDeGrafico.getPanel();
        painel_grafico.add(grafico, BorderLayout.CENTER);
        painel_grafico.validate();
    }//GEN-LAST:event_gerarGeralMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ano_label;
    private javax.swing.JTextPane console;
    private javax.swing.JScrollPane console_panel;
    private javax.swing.JLabel data_fim_label;
    private javax.swing.JFormattedTextField data_fim_text;
    private javax.swing.JFormattedTextField data_formatada;
    private javax.swing.JLabel data_inicio_label;
    private javax.swing.JFormattedTextField data_inicio_text;
    private javax.swing.JLabel data_label;
    private javax.swing.JLabel endereco_label;
    private javax.swing.JTextField endereco_texto;
    private javax.swing.JPanel geral;
    private javax.swing.JButton gerarGeral;
    private javax.swing.JTextArea grafico_parquimetro;
    private javax.swing.JPanel graficos;
    private javax.swing.JPanel importarInserir;
    private javax.swing.JButton importarLogging;
    private javax.swing.JButton inserirDados;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JTabbedPane moduloGerencial;
    private java.awt.Panel painel_grafico;
    private javax.swing.JLabel parquimetro_grafico;
    private javax.swing.JComboBox<String> parquimetro_selecionado;
    private javax.swing.JPanel porParquimetro;
    private javax.swing.JTextArea relatorio;
    private javax.swing.JPanel relatorios;
    private javax.swing.JScrollPane scroll_parquimetro;
    private javax.swing.JScrollPane scroll_relatorios;
    private javax.swing.JLabel seletor_parquimetro;
    private javax.swing.JComboBox<String> seletor_parquimetro_grafico;
    private javax.swing.JTabbedPane subgraficos;
    // End of variables declaration//GEN-END:variables
 
}
